[CSR-4778] Update date component
TimeChimp/tacugama pull request #1421
Opened 2024-04-03 15:13 UTC by OksanaTC

[Link to CSR-4778](https://timechimp.atlassian.net/browse/CSR-4778)

2024-04-15 11:07 UTC, dylanmau requested changes
Nice!
Just some general ux changes I discussed with Niki: 
- Not sure how easy it is to achieve but it would be nice if when you type in a date manually, it will automatically put it in a correct format ( so while you typing it will by default add a / separator after typing in two digits )  
- Also the placeholder shows a different date format then the date that you put in.

2024-04-17 08:35 UTC, dylanmau approved these changes

2024-04-17 08:37 UTC, tarashaidarTimechimp approved these changes

2024-04-17 08:57 UTC, hiddeottens requested changes

2024-04-17 08:57 UTC, hiddeottens commented on src/components/data-grid/filters/ColumnFilters.tsx
> +import { CustomDatepicker } from 'components/datepicker';
```suggestion
import { CustomDatepicker } from '../../datepicker';
```

2024-04-17 08:57 UTC, hiddeottens commented on src/components/datepicker/CustomDatepicker.tsx
> +import { FlexItem } from 'components/flex-item';
All paths should be relative otherwise it doesn't work in common.js

2024-04-17 09:13 UTC, hiddeottens approved these changes

2024-04-17 09:14 UTC, merged