feat(CSR-1019): add attachment hendling
TimeChimp/tacugama pull request #526
Opened 2021-09-03 12:41 UTC by Ihor-Lavrov

2021-09-03 13:15 UTC, jackinf approved these changes

2021-09-06 07:11 UTC, bogdankf1 approved these changes

2021-09-06 08:15 UTC, hiddeottens requested changes

2021-09-06 08:15 UTC, hiddeottens commented on src/components/attachments-list/AttachemntsList.tsx
> +import React from 'react';
filename should be `AttachmentsList.tsx`

2021-09-06 08:15 UTC, hiddeottens commented on src/components/icons/FileAttachments.tsx
> +          fill-rule="evenodd"
```suggestion
          fillRule="evenodd"
```

2021-09-06 08:15 UTC, hiddeottens commented on src/components/icons/FileAttachments.tsx
> +          clip-rule="evenodd"
```suggestion
          clipRule="evenodd"
```

2021-09-06 10:51 UTC, merged