Feat/csr 3760/styling aggrid
TimeChimp/tacugama pull request #995
Opened 2023-03-13 15:46 UTC by dylanmau

https://timechimp.atlassian.net/jira/software/c/projects/CSR/boards/19/backlog?view=detail&selectedIssue=CSR-3760&issueLimit=100&assignee=63ff4d19314f50881381751a

2023-03-15 13:27 UTC, hiddeottens commented on src/components/data-grid/styles.ts
> +      --ag-row-hover-color: ${theme.customColors.light7};
What about the theme coloring?

2023-03-17 10:14 UTC, hiddeottens requested changes
some minor styling changes

2023-03-17 10:14 UTC, hiddeottens commented on src/components/data-grid/styles.ts
> +      --ag-row-hover-color: ${theme.customColors.light7};
```suggestion
      --ag-row-hover-color: ${theme.colors.primary50};
```

2023-03-17 10:14 UTC, hiddeottens commented on src/components/data-grid/styles.ts
> +      --ag-selected-row-background-color: ${theme.colors.primary}0f;
```suggestion
      --ag-selected-row-background-color: ${theme.colors.primary100};
```

2023-03-17 12:39 UTC, dylanmau commented on src/components/data-grid/styles.ts
> +      --ag-selected-row-background-color: ${theme.colors.primary}0f;
Changed it

2023-03-17 12:43 UTC, hiddeottens approved these changes

2023-03-17 12:50 UTC, merged